### ISSUE TITLE
node-oracledb 1.9-dev has native promise support

### ISSUE THREAD

**Issue by cjbj** [toberoo/promise-oracledb#4]
Check out the native promise support in the development branch of node-oracledb: https://github.com/oracle/node-oracledb/tree/dev-1.9

Comments on the design and implementation are welcome at oracle/node-oracledb#410

**Comment by toberoo** [comment]
Sounds good. Thanks for the headsup.

**Comment by cjbj** [comment]
Give it a whirl and let us know whether it does what you want.
